# -*- coding: utf-8 -*-
"""child_adult.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZtFZpROPpFXLwevdWCzdpZ_xBrgpoy0r
"""

!unzip combined_datasets_withokinawa.zip > /dev/null

!zip -r labels.zip images_fix/labels/

import os
import random
import shutil
from pathlib import Path

# === 設定 ===
image_dir = "combined_datasets/images"        # 画像が入っているフォルダ
label_dir = "combined_datasets/labels"    # アノテーションが入っているフォルダ
output_dir = "dataset_split"

# 対応する拡張子
image_ext = ".jpg"
label_ext = ".txt"

# train:val:test の比率
split_ratio = [0.8, 0.1, 0.1]

# 乱数シード
seed = 42

# === スクリプト ===
def main():
    random.seed(seed)
    # 出力フォルダ作成
    for split in ["train", "val", "test"]:
        os.makedirs(os.path.join(output_dir, "images", split), exist_ok=True)
        os.makedirs(os.path.join(output_dir, "labels", split), exist_ok=True)

    # 画像一覧を取得
    images = [f for f in os.listdir(image_dir) if f.endswith(image_ext)]
    images.sort()  # 同じ環境で再現性を高めるため一度ソート
    random.shuffle(images)

    n_total = len(images)
    n_train = int(n_total * split_ratio[0])
    n_val   = int(n_total * split_ratio[1])
    # 残りを test に
    n_test  = n_total - n_train - n_val

    splits = {
        "train": images[:n_train],
        "val":   images[n_train:n_train+n_val],
        "test":  images[n_train+n_val:]
    }

    # コピー実行
    for split, files in splits.items():
        for img_file in files:
            base = Path(img_file).stem
            anno_file = base + label_ext

            # コピー
            shutil.copy(os.path.join(image_dir, img_file),
                        os.path.join(output_dir, "images", split, img_file))

            if os.path.exists(os.path.join(label_dir, anno_file)):
                shutil.copy(os.path.join(label_dir, anno_file),
                            os.path.join(output_dir, "labels", split, anno_file))

    print("Done!")
    print(f"train: {len(splits['train'])}, val: {len(splits['val'])}, test: {len(splits['test'])}")

if __name__ == "__main__":
    main()

!pip install ultralytics > /dev/null

from ultralytics import YOLO

# Load a model
model = YOLO("yolo11n.yaml")  # build a new model from YAML
model = YOLO("yolo11n.pt")  # load a pretrained model (recommended for training)
model = YOLO("yolo11n.yaml").load("yolo11n.pt")  # build from YAML and transfer weights

!pwd

# Train the model
model.train(data="/content/combined_datasets/adult_child.yaml", epochs=80, imgsz=640)

best_model = YOLO("runs/detect/train2/weights/best.pt")

from IPython.display import Image

Image(filename="runs/detect/train2/results.png", width=800)

# results = best_model.predict(source="screenshot.png", save=True)

results = best_model.predict(source="/content/dataset_split/images/test/", save=True)

!unzip okinawa_202510.zip > /dev/null

!unzip combined_datasets.zip > /dev/null

# fine tuning
import os, random, shutil
from pathlib import Path

combined_dir = "finetuning_split"
output_dir = "finetuning_split_"
split_ratio = 0.8  # train:val = 8:2
seed = 42
random.seed(seed)

def main():
    imgs = [f for f in os.listdir(os.path.join(combined_dir, "images")) if f.endswith(".jpg")]
    random.shuffle(imgs)

    n_train = int(len(imgs) * split_ratio)
    train_imgs = imgs[:n_train]
    val_imgs = imgs[n_train:]

    for split, files in [("train", train_imgs), ("val", val_imgs)]:
        os.makedirs(os.path.join(output_dir, "images", split), exist_ok=True)
        os.makedirs(os.path.join(output_dir, "labels", split), exist_ok=True)

        for img_file in files:
            base = Path(img_file).stem
            lbl_file = base + ".txt"

            shutil.copy(os.path.join(combined_dir, "images", img_file),
                        os.path.join(output_dir, "images", split, img_file))
            shutil.copy(os.path.join(combined_dir, "labels", lbl_file),
                        os.path.join(output_dir, "labels", split, lbl_file))

    print(f"train: {len(train_imgs)}, val: {len(val_imgs)}")

if __name__ == "__main__":
    main()

from ultralytics import YOLO

best_model = YOLO("20250924_best.pt")

# Train the model
best_model.train(data="/content/combined_datasets/adult_child.yaml", epochs=20, lr0=0.0005, imgsz=640)

from IPython.display import Image

Image(filename="runs/detect/train/results.png", width=800)
