# -*- coding: utf-8 -*-
"""generate_heatmap.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AW7EHHDZXSn4ZUTcaOc91J_C7YvCiJeo
"""

from google.colab import userdata

!pip install ultralytics > /dev/null

"""### google drive をマウント"""

from google.colab import drive
drive.mount('/content/drive')

"""## settings for google colab"""

# 任意のパス
save_base_path = '/content/drive/MyDrive/HETech/output/heatmap/'

import os
os.environ['GITHUB_USERNAME'] = "shayaf"
# NOTE: GitHub Token はハードコードせず、外部から渡してください... Colabの secret など
os.environ['GITHUB_TOKEN'] = userdata.get('github_accesstoken')

repo_url = f"https://{os.environ['GITHUB_USERNAME']}:{os.environ['GITHUB_TOKEN']}@github.com/H-E-Technology/python-codes.git"

"""## git clone"""

!git clone $repo_url

"""## execution"""

# Commented out IPython magic to ensure Python compatibility.
# %cd python-codes/person_re_id/

!pwd

!cp bytetrack.yaml /usr/local/lib/python*/dist-packages/ultralytics/cfg/trackers/
!cp botsort.yaml /usr/local/lib/python*/dist-packages/ultralytics/cfg/trackers/

# 遮蔽時以外の re-id を減らす処理を追加している
!cp bot_sort.py /usr/local/lib/python*/dist-packages/ultralytics/trackers/bot_sort.py

"""### 実行前の注意
- 長い動画は fps を下げても問題ない場合が多い -> 下の fps 下げるスクリプトを活用。

- /content/python-codes/person_re_id/config.yaml の確認
    - l.60 fps設定を入力動画と同じ fps にする
"""

# model は google drive から取得する
!python yolo_multi_model_refactored.py \
  --source "/content/2025-10-21_10-26-35_5fps.mp4" \
  --track \
  --model "/content/finetuning_okinawa.pt" \
  --dataset-yaml "adult_child.yaml" \
  --classes "0,1"

# outputをzip化
!zip -r /content/output_all.zip /content/python-codes/person_re_id/output

# Driveに移動
!mv /content/output_all.zip $save_base_path

"""## 動画の fps を下げるスクリプト🍴"""

import cv2

input_path = "/content/2025-10-21_10-26-35.mp4"
output_path = "/content/2025-10-21_10-26-35_5fps.mp4"

# 読み込み
cap = cv2.VideoCapture(input_path)
fps_in = cap.get(cv2.CAP_PROP_FPS)
frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

# 出力fps
fps_out = 5

# VideoWriter
fourcc = cv2.VideoWriter_fourcc(*'mp4v')
out = cv2.VideoWriter(output_path, fourcc, fps_out, (w, h))

# 間引き計算
skip = int(round(fps_in / fps_out))
frame_idx = 0

while True:
    ret, frame = cap.read()
    if not ret:
        break

    # fps_out に合わせて書き出し
    if frame_idx % skip == 0:
        out.write(frame)

    frame_idx += 1

cap.release()
out.release()

print(f"✅ Done! {input_path} を {fps_out}fps に変換しました: {output_path}")

